//! Dump the **authoring platform's** half of its freeze manifest as JSON — slice 8 of the
//! reference flip (`docs/plans/post-roadmap-reference-flip.md`).
//!
//! The counterpart of `dump_biosphere_inventory` / `dump_station_inventory`, and it landed
//! in one step rather than two: those two were built in slice 3 as *witnesses* (a Python
//! gate checked them against a Python-generated manifest) and promoted to *producers* in
//! slices 6 and 7. Slice 3 deliberately left this contract out, so this program is a
//! producer from its first commit — `tests/test_authoring_freeze_manifest.py::_build_manifest()`
//! shells it and splices the keys below in.
//!
//! ⚠⚠ **Read `authoring::surface`'s module docs before trusting the word "derived" here.**
//! The other two dumps enumerate a **built registry**: they ask a canonical scenario which
//! flows it actually wired. This contract freezes the *platform*, which has no such
//! runtime object, and Python's derivation of it uses language introspection Rust does not
//! have (`typing.get_args`, a scan of `vars(module)`, pydantic `model_fields`, a dict).
//! Every axis below is therefore part derived and part hand-maintained roster, and which
//! is which is stated per key in the manifest's `_authority` block. **A green run of this
//! program is not the same evidence a green `dump_station_inventory` is.**
//!
//! ## What is emitted
//!
//! * `expr_nodes` / `binary_ops` — the grammar's node and operator vocabulary. Names come
//!   from an exhaustive `match` (a new `Expr` variant is a compile error) and symbols from
//!   `BinaryOp::symbol()`; the *rosters* of variants are hand-maintained.
//! * `ref_keywords` / `step_token` — the parser's own tables, load-bearing: these are the
//!   values `expr_parser` tests an identifier against, so changing one changes what the
//!   platform parses.
//! * `schema_fields` — the eight `reject_unknown_keys` key sets, likewise load-bearing.
//!   The spec *labels* are Python class names typed by hand (two of them name no Rust type
//!   at all).
//! * `flow_types` / `param_loaders` — the author-selectable registry. Each entry is read
//!   off its `FlowTypeSpec`, and `cls` off a flow this program **constructs** through
//!   `build_frozen_flow`, so it is the class the registry would really instantiate.
//! * `integrator_names` / `rate_classes` — the legal `integrator:` and `rate_class:`
//!   vocabularies.
//!
//! ## What is deliberately NOT emitted
//!
//! * ⚠ **`parity_vectors`** — the sha-256s of `parse_vectors.txt` / `traj_vectors.txt`.
//!   Those files live in *this crate's* `tests/data`, which makes it tempting; but they are
//!   **generated by Python** (`tests/crossport/gen_authoring_vectors.py`) and re-derived
//!   here as the parity check. Hashing them from this side would make the gate compare the
//!   checker's output with itself — `param_files`' shape (slice 3), reached by a different
//!   road. ⚠ Under the target state the user restated on 2026-08-17 (Rust is the project;
//!   Python survives as the external-software oracle and as rewrite scaffolding) these
//!   generators are squarely scaffolding, and moving them is a successor item, not a rider
//!   on this ceremony.
//! * **`grammar_note`, `_comment`, `frozen_at_phase`, `reference_doc`, `delegates_to`** —
//!   prose, labels and pointers. Neither port derives them and neither should.

use authoring::surface;

fn quote(s: &str) -> String {
    format!("\"{s}\"")
}

fn json_str_array<'a>(items: impl IntoIterator<Item = &'a str>) -> String {
    let items: Vec<String> = items.into_iter().map(quote).collect();
    format!("[{}]", items.join(", "))
}

fn main() {
    let mut out = String::new();
    out.push_str("{\n");

    out.push_str(&format!(
        "  \"binary_ops\": {},\n",
        json_str_array(surface::binary_ops())
    ));
    out.push_str(&format!(
        "  \"expr_nodes\": {},\n",
        json_str_array(surface::expr_nodes())
    ));

    // --- flow_types -------------------------------------------------------
    out.push_str("  \"flow_types\": {\n");
    let types = surface::flow_types();
    let last = types.len() - 1;
    for (i, (name, spec)) in types.iter().enumerate() {
        let param_set = match spec.param_set {
            Some(p) => quote(p),
            None => "null".to_string(),
        };
        let demand = match spec.demand_controlled {
            Some((field, param)) => format!("[{}, {}]", quote(field), quote(param)),
            None => "null".to_string(),
        };
        out.push_str(&format!("    {}: {{\n", quote(name)));
        out.push_str(&format!("      \"cls\": {},\n", quote(spec.cls)));
        out.push_str(&format!("      \"demand_controlled\": {demand},\n"));
        out.push_str(&format!("      \"param_set\": {param_set},\n"));
        out.push_str(&format!(
            "      \"rate_params\": {},\n",
            json_str_array(spec.rate_params.iter().copied())
        ));
        out.push_str(&format!(
            "      \"wiring_fields\": {}\n",
            json_str_array(spec.wiring_fields.iter().copied())
        ));
        out.push_str(if i == last { "    }\n" } else { "    },\n" });
    }
    out.push_str("  },\n");

    out.push_str(&format!(
        "  \"integrator_names\": {},\n",
        json_str_array(surface::integrator_names())
    ));
    out.push_str(&format!(
        "  \"param_loaders\": {},\n",
        json_str_array(surface::param_loaders())
    ));
    out.push_str(&format!(
        "  \"rate_classes\": {},\n",
        json_str_array(surface::rate_classes())
    ));
    out.push_str(&format!(
        "  \"ref_keywords\": {},\n",
        json_str_array(surface::ref_keywords())
    ));

    // --- schema_fields ----------------------------------------------------
    out.push_str("  \"schema_fields\": {\n");
    let fields = surface::schema_fields();
    let last = fields.len() - 1;
    for (i, (label, keys)) in fields.iter().enumerate() {
        let comma = if i == last { "" } else { "," };
        out.push_str(&format!(
            "    {}: {}{comma}\n",
            quote(label),
            json_str_array(keys.iter().copied())
        ));
    }
    out.push_str("  },\n");

    out.push_str(&format!(
        "  \"step_token\": {}\n",
        quote(surface::STEP_TOKEN)
    ));
    out.push_str("}\n");

    // Tier-0 sanity on the program itself, on the axes where an empty answer would be a
    // false claim rather than a legitimate one. ⚠ Unlike the station dump's `aux_set`
    // there is no legitimately-empty axis here — every set below is non-empty by the
    // contract's own definition — so these assertions are cheap and honest.
    assert!(!surface::expr_nodes().is_empty(), "no grammar nodes");
    assert!(!surface::flow_types().is_empty(), "no flow types");
    assert!(!surface::schema_fields().is_empty(), "no spec models");

    print!("{out}");
}
