//! Weather → flow-driver conversions — the Rust port of `domains.biosphere.weather`
//! (+ the SVP primitive Python locates in `transpiration`) (Phase-7 P7.4).
//!
//! The **heaviest libm-audit surface** of the port (plan Step 4): `daylength_seconds`
//! (sin/tan/acos), `saturation_vapor_pressure`/`vapor_pressure_deficit` (exp),
//! `incident_par`, `net_radiation`. The raw NASAPower facts arrive from the committed
//! `weather_facts.txt` (generated by `gen_biosphere_weather.py`); these conversions run
//! **in Rust**, so the transcendentals are exercised cross-port. Every op mirrors the
//! Python source character-for-character (`math.radians`→`.to_radians()`,
//! `math.sin`→`.sin()`, …).

use std::f64::consts::PI;

use simcore::hexfloat;

/// The committed raw-weather facts (see `gen_biosphere_weather.py`).
const WEATHER_FACTS: &str = include_str!("weather_facts.txt");

const SECONDS_PER_DAY: f64 = 86400.0;
/// PAR is ~50% of global shortwave by energy (McCree 1972; FAO uses 0.5).
const PAR_ENERGY_FRACTION: f64 = 0.5;
/// PAR photon flux per unit PAR energy: ~4.57 µmol photons per J (McCree 1972).
const PAR_UMOL_PER_J: f64 = 4.57;
/// FAO-56 reference-crop albedo (net shortwave Rns = (1 − α)·Rs).
const ALBEDO: f64 = 0.23;

// Saturation-vapour-pressure constants (Tetens / FAO-56); Python locates these in
// `transpiration`. e_s(T) = SVP_A · exp(SVP_B · T / (T + SVP_C))  [Pa], T in °C.
/// Tetens/FAO-56 SVP pre-factor (Pa).
pub const SVP_A: f64 = 610.8;
/// Tetens/FAO-56 SVP exponent numerator coefficient (dimensionless).
pub const SVP_B: f64 = 17.27;
/// Tetens/FAO-56 SVP exponent denominator offset (°C).
pub const SVP_C: f64 = 237.3;

/// One raw daily weather fact (day-of-year + the three NASAPower observations).
#[derive(Debug, Clone, Copy)]
pub struct WeatherRow {
    pub day_of_year: i64,
    pub temp_c: f64,
    pub irrad_j_m2_day: f64,
    pub vap_hpa: f64,
}

/// Parse the embedded facts file into `(latitude, rows)`.
pub fn weather_facts() -> (f64, Vec<WeatherRow>) {
    let mut latitude: Option<f64> = None;
    let mut rows: Vec<WeatherRow> = Vec::new();
    for line in WEATHER_FACTS.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut fields = line.split('\t');
        let head = fields.next().expect("weather line has a leading field");
        if head == "latitude" {
            latitude = Some(
                hexfloat::parse(fields.next().expect("latitude value"))
                    .expect("latitude hex-float parses"),
            );
        } else {
            let doy: i64 = head.parse().expect("day-of-year is an integer");
            let mut hf = || {
                hexfloat::parse(fields.next().expect("weather field"))
                    .expect("weather hex-float parses")
            };
            rows.push(WeatherRow {
                day_of_year: doy,
                temp_c: hf(),
                irrad_j_m2_day: hf(),
                vap_hpa: hf(),
            });
        }
    }
    (latitude.expect("weather_facts.txt has a latitude line"), rows)
}

/// Astronomical daylight duration (s) from latitude + day-of-year (FAO-56). Mirrors
/// `weather.daylength_seconds` op-for-op — the sin/tan/acos libm surface.
pub fn daylength_seconds(latitude_deg: f64, day_of_year: i64) -> f64 {
    let phi = latitude_deg.to_radians();
    let decl = 0.409 * (2.0 * PI * (day_of_year as f64) / 365.0 - 1.39).sin();
    let arg = -phi.tan() * decl.tan();
    // Clamp for polar latitudes — Python `max(-1.0, min(1.0, arg))`; `.clamp` is
    // bit-identical for the finite args here (it selects arg / 1.0 / -1.0, no arithmetic).
    let arg = arg.clamp(-1.0, 1.0);
    let sunset_hour_angle = arg.acos();
    let daylight_hours = 24.0 / PI * sunset_hour_angle;
    daylight_hours * 3600.0
}

/// Daytime-mean incident PAR photon flux (µmol m⁻² s⁻¹) from daily IRRAD.
pub fn incident_par(irrad_j_m2_day: f64, daylength_s: f64) -> f64 {
    let mean_par_irradiance = PAR_ENERGY_FRACTION * irrad_j_m2_day / daylength_s;
    mean_par_irradiance * PAR_UMOL_PER_J
}

/// Daily-mean net radiation (W m⁻²) ≈ net shortwave (1 − α)·Rs (FAO-56).
pub fn net_radiation(irrad_j_m2_day: f64) -> f64 {
    let shortwave = irrad_j_m2_day / SECONDS_PER_DAY;
    (1.0 - ALBEDO) * shortwave
}

/// Saturation vapour pressure e_s = A·exp(B·T/(T+C)) (Pa; Tetens/FAO-56). Python locates
/// this in `transpiration`; the port keeps it here (its first consumer, the VPD build).
pub fn saturation_vapor_pressure(temp_c: f64) -> f64 {
    SVP_A * (SVP_B * temp_c / (temp_c + SVP_C)).exp()
}

/// Vapour-pressure deficit (Pa) from air temperature + actual vapour pressure.
pub fn vapor_pressure_deficit(temp_c: f64, vap_hpa: f64) -> f64 {
    let e_a = vap_hpa * 100.0; // hPa -> Pa
    (saturation_vapor_pressure(temp_c) - e_a).max(0.0)
}

/// The per-day forcing tables the season resolver reads, tiled over `years`. Each Vec has
/// length `rows.len()·years` (the Python `weather = _weather()*years` tiling), so a
/// clamping `_table`-style index reproduces the reference exactly.
#[derive(Debug, Clone)]
pub struct ForcingTables {
    pub temp: Vec<f64>,
    pub par: Vec<f64>,
    pub daylength: Vec<f64>,
    pub net_radiation: Vec<f64>,
    pub vpd: Vec<f64>,
}

/// Build the tiled forcing tables from the raw facts (the `weather_resolver` precompute).
pub fn season_forcing(latitude: f64, rows: &[WeatherRow], years: usize) -> ForcingTables {
    let mut temp = Vec::with_capacity(rows.len() * years);
    let mut par = Vec::with_capacity(rows.len() * years);
    let mut daylength = Vec::with_capacity(rows.len() * years);
    let mut rn = Vec::with_capacity(rows.len() * years);
    let mut vpd = Vec::with_capacity(rows.len() * years);
    // Convert once per row, then tile — identical to Python's convert-of-tiled-rows since
    // each conversion is a pure function of the row (and the shared latitude).
    let mut base_temp = Vec::with_capacity(rows.len());
    let mut base_par = Vec::with_capacity(rows.len());
    let mut base_dl = Vec::with_capacity(rows.len());
    let mut base_rn = Vec::with_capacity(rows.len());
    let mut base_vpd = Vec::with_capacity(rows.len());
    for row in rows {
        let dl = daylength_seconds(latitude, row.day_of_year);
        base_temp.push(row.temp_c);
        base_dl.push(dl);
        base_par.push(incident_par(row.irrad_j_m2_day, dl));
        base_rn.push(net_radiation(row.irrad_j_m2_day));
        base_vpd.push(vapor_pressure_deficit(row.temp_c, row.vap_hpa));
    }
    for _ in 0..years {
        temp.extend_from_slice(&base_temp);
        par.extend_from_slice(&base_par);
        daylength.extend_from_slice(&base_dl);
        rn.extend_from_slice(&base_rn);
        vpd.extend_from_slice(&base_vpd);
    }
    ForcingTables {
        temp,
        par,
        daylength,
        net_radiation: rn,
        vpd,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn facts_parse_305_rows() {
        let (lat, rows) = weather_facts();
        assert_eq!(lat, 52.0);
        assert_eq!(rows.len(), 305);
        assert_eq!(rows[0].day_of_year, 274); // 2006-10-01
    }

    #[test]
    fn equator_daylength_is_12h() {
        // ωs = π/2 at the equator ⇒ exactly 12 h = 43200 s for every day.
        assert!((daylength_seconds(0.0, 100) - 43200.0).abs() < 1e-6);
    }
}
