//! Extinction with a loss-sink (decision #6) — the Rust port of `tests/test_extinction.py`
//! (Stage-3 slice S4), and the discharge of **FINDING 7's** older sibling, FINDING 6.
//!
//! ## Why this file exists at all
//!
//! Extinction is one of `CLAUDE.md`'s non-negotiable invariants: a POPULATION stock below
//! its threshold snaps to exactly 0 and the residual routes to the quantity's
//! numerical-loss sink, so the ledger still balances. `integrator.rs`'s `extinction_pass`
//! implements it, and before this file **no Rust test named it**. The plan's first draft
//! said it was untested; a control falsified that and produced the narrower, more useful
//! statement: disabling the branch reddens exactly one test,
//! `engine_vectors.rs::engine_synthetic_trajectory_is_bit_exact`, on the
//! `boundary.loss.carbon` leaf at step 16. So extinction was held by a single bit-exact
//! trajectory vector that pins the whole state — it reports *that something changed*,
//! never *which mechanism broke* — and that vector file is generated by
//! `tests/crossport/gen_engine_vectors.py`, a generator queued for deletion in S6.
//!
//! Every case below is therefore a by-name claim about the mechanism, reachable without
//! the vector file.
//!
//! ## Both halves of the invariant, and the second one is the one that ports as prose
//!
//! *"POPULATION stock below threshold → 0 with the residual routed to the loss-sink"* has
//! an inseparable negative clause — *"POOL stocks are never zeroed-with-loss"*. A gate
//! that asserts only the positive half passes an implementation that snaps everything.
//! [`a_pool_below_threshold_is_never_zeroed`] is that clause.

use std::collections::BTreeMap;

use simcore::boundary;
use simcore::environment::{Environment, SourceResolver};
use simcore::error::SimError;
use simcore::flow::{assert_flow_balanced_default, Flow, FlowResult, Leg};
use simcore::integrator::{EulerIntegrator, Rk4Integrator, StepReport};
use simcore::quantities::{Quantity, StockKind};
use simcore::registry::Registry;
use simcore::state::{State, Stock};

const P: &str = "bio.pop";
const SRC: &str = "boundary.src_c";

/// The two schemes, as a value — `StepIntegrator` (the trait that would let one function
/// take either) lives in `domains`, one crate *above* this one, so a `simcore` test that
/// wants the Python `@parametrize("integrator_cls", [Euler, Rk4])` axis dispatches by hand.
/// Recorded rather than worked around: the shared step interface is not in the core.
#[derive(Debug, Clone, Copy)]
enum Scheme {
    Euler,
    Rk4,
}

impl Scheme {
    fn step_report(
        self,
        registry: Registry,
        state: &State,
        env: &SourceResolver,
        dt: f64,
    ) -> Result<StepReport, SimError> {
        match self {
            Scheme::Euler => EulerIntegrator::new(registry).step_report(state, env, dt),
            Scheme::Rk4 => Rk4Integrator::new(registry).step_report(state, env, dt),
        }
    }
}

fn population(amount: f64, threshold: f64) -> Stock {
    Stock::new(
        P.to_string(),
        "bio".to_string(),
        Quantity::Carbon,
        Quantity::Carbon.canonical_unit(),
        amount,
        StockKind::Population,
        threshold,
        false,
        BTreeMap::new(),
    )
    .expect("population stock")
}

fn stocks_of(list: Vec<Stock>) -> BTreeMap<String, Stock> {
    list.into_iter().map(|s| (s.id.clone(), s)).collect()
}

fn state_of(stocks: &BTreeMap<String, Stock>) -> State {
    State::new(0, stocks.clone(), 0, BTreeMap::new()).expect("state")
}

/// Deposits a fixed `amount` per `dt` into `dst` from an **unclamped** source (decision
/// #13), so it is never throttled and never trips the RK4 over-draw guard — which is what
/// lets these cases isolate extinction from arbitration.
struct DepositFlow {
    id: String,
    src: String,
    dst: String,
    amount: f64,
}

impl Flow for DepositFlow {
    fn type_name(&self) -> &'static str {
        "DepositFlow"
    }

    fn id(&self) -> &str {
        &self.id
    }

    fn evaluate(&self, _snapshot: &State, _env: &dyn Environment, dt: f64) -> Result<FlowResult, SimError> {
        let x = self.amount * dt;
        FlowResult::new(vec![
            Leg::new(self.src.clone(), -x)?,
            Leg::new(self.dst.clone(), x)?,
        ])
    }
}

// --------------------------------------------------------------------------- //
// The basic snap — scheme-independent                                          //
// --------------------------------------------------------------------------- //

fn below_threshold_snaps_and_routes(scheme: Scheme) {
    let ls = boundary::loss_sink(Quantity::Carbon, 0.0).expect("loss sink");
    let ls_id = boundary::loss_sink_id(Quantity::Carbon);
    let stocks = stocks_of(vec![population(0.3, 0.5), ls]);
    let state = state_of(&stocks);

    let report = scheme
        .step_report(
            Registry::flows_only(Vec::new(), &stocks).expect("registry"),
            &state,
            &SourceResolver::empty(),
            1.0,
        )
        .expect("step");

    assert_eq!(report.state.stocks[P].amount, 0.0, "{scheme:?}: snapped to exactly 0");
    assert_eq!(
        report.state.stocks[&ls_id].amount, 0.3,
        "{scheme:?}: the residual is routed, not discarded"
    );
    assert_eq!(report.events.len(), 1, "{scheme:?}: one event");
    let ev = &report.events[0];
    assert_eq!(ev.stock, P);
    assert_eq!(ev.quantity, Quantity::Carbon);
    assert_eq!(ev.residual, 0.3);
    assert_eq!(ev.n, 1, "{scheme:?}: the event carries the post-apply step count");

    // The ledger closes: the population's loss is exactly the loss-sink's gain.
    let delta = FlowResult::new(vec![
        Leg::new(P.to_string(), report.state.stocks[P].amount - 0.3).unwrap(),
        Leg::new(ls_id.clone(), report.state.stocks[&ls_id].amount - 0.0).unwrap(),
    ])
    .unwrap();
    assert_flow_balanced_default(&delta, &state.stocks).expect("the snap conserves mass");
}

#[test]
fn a_population_below_threshold_snaps_to_zero_and_routes_its_residual_under_euler() {
    below_threshold_snaps_and_routes(Scheme::Euler);
}

#[test]
fn a_population_below_threshold_snaps_to_zero_and_routes_its_residual_under_rk4() {
    below_threshold_snaps_and_routes(Scheme::Rk4);
}

/// The negative clause. A POOL carries an `extinction_threshold` field but is exempt —
/// extinction is POPULATION-only — so it must pass through untouched. Without this, an
/// implementation that snapped *every* below-threshold stock would satisfy every other case
/// in this file.
///
/// ⚠ The loss-sink is present **deliberately**, though nothing here routes into it. Without
/// it, an implementation that wrongly snapped POOLs would fail this case with a *reference*
/// error about an absent sink — caught, but for the wrong reason, and the diagnostic would
/// misname the defect. With the sink in place the failure is the assertion below.
#[test]
fn a_pool_below_threshold_is_never_zeroed() {
    let pool = Stock::new(
        P.to_string(),
        "bio".to_string(),
        Quantity::Carbon,
        Quantity::Carbon.canonical_unit(),
        0.3,
        StockKind::Pool,
        0.5,
        false,
        BTreeMap::new(),
    )
    .expect("pool");
    let ls_id = boundary::loss_sink_id(Quantity::Carbon);
    let stocks = stocks_of(vec![pool, boundary::loss_sink(Quantity::Carbon, 0.0).unwrap()]);
    let state = state_of(&stocks);

    let report = EulerIntegrator::new(Registry::flows_only(Vec::new(), &stocks).unwrap())
        .step_report(&state, &SourceResolver::empty(), 1.0)
        .expect("step");

    assert_eq!(report.state.stocks[P].amount, 0.3, "the POOL was snapped");
    assert_eq!(report.state.stocks[&ls_id].amount, 0.0, "and nothing was routed to loss");
    assert!(report.events.is_empty(), "a POOL emits no extinction event");
}

// --------------------------------------------------------------------------- //
// Absorbing: no event-spam, no revival from sub-threshold noise                //
// --------------------------------------------------------------------------- //

/// Sitting at exactly 0 below a positive threshold must not re-emit an event or re-route
/// every step — the `amount != 0` guard. No loss-sink is even needed, which is itself the
/// assertion: a re-fire would raise for the missing sink.
#[test]
fn an_already_extinct_stock_does_not_refire() {
    let stocks = stocks_of(vec![population(0.0, 0.5)]);
    let state = state_of(&stocks);

    let report = EulerIntegrator::new(Registry::flows_only(Vec::new(), &stocks).unwrap())
        .step_report(&state, &SourceResolver::empty(), 1.0)
        .expect("step");

    assert_eq!(report.state.stocks[P].amount, 0.0);
    assert!(report.events.is_empty());
}

/// An extinct stock receives a sub-threshold "noise" inflow of 0.1 (< 0.5). After apply it
/// holds 0.1; the extinction pass re-snaps it to 0 and routes the 0.1 — it does **not**
/// revive. Whole-step mass still conserves: the source gave 0.1, the loss-sink absorbed it.
#[test]
fn a_subthreshold_inflow_is_resnapped_rather_than_reviving_the_stock() {
    let ls_id = boundary::loss_sink_id(Quantity::Carbon);
    let stocks = stocks_of(vec![
        population(0.0, 0.5),
        boundary::source(SRC.to_string(), Quantity::Carbon, 1000.0, true).unwrap(),
        boundary::loss_sink(Quantity::Carbon, 0.0).unwrap(),
    ]);
    let state = state_of(&stocks);
    let flow = DepositFlow {
        id: "noise".to_string(),
        src: SRC.to_string(),
        dst: P.to_string(),
        amount: 0.1,
    };

    let report = EulerIntegrator::new(Registry::flows_only(vec![Box::new(flow)], &stocks).unwrap())
        .step_report(&state, &SourceResolver::empty(), 1.0)
        .expect("step");

    assert_eq!(report.state.stocks[P].amount, 0.0, "re-snapped, not revived");
    assert!((report.state.stocks[&ls_id].amount - 0.1).abs() < 1e-12);
    assert_eq!(report.events.len(), 1);
    let src_delta = report.state.stocks[SRC].amount - 1000.0;
    assert!((src_delta + 0.1).abs() < 1e-12, "the source supplied exactly 0.1");
}

/// A scenario-scale inflow of 1.0 (>= 0.5) revives the stock: it stays alive and emits no
/// event. The pair with the case above is what makes the threshold a *threshold* rather
/// than a one-way trap.
#[test]
fn a_suprathreshold_inflow_survives() {
    let stocks = stocks_of(vec![
        population(0.0, 0.5),
        boundary::source(SRC.to_string(), Quantity::Carbon, 1000.0, true).unwrap(),
        boundary::loss_sink(Quantity::Carbon, 0.0).unwrap(),
    ]);
    let state = state_of(&stocks);
    let flow = DepositFlow {
        id: "reintroduce".to_string(),
        src: SRC.to_string(),
        dst: P.to_string(),
        amount: 1.0,
    };

    let report = EulerIntegrator::new(Registry::flows_only(vec![Box::new(flow)], &stocks).unwrap())
        .step_report(&state, &SourceResolver::empty(), 1.0)
        .expect("step");

    assert!((report.state.stocks[P].amount - 1.0).abs() < 1e-12);
    assert!(report.events.is_empty());
}

// --------------------------------------------------------------------------- //
// Referential integrity: routing into a loss-sink that is not there            //
// --------------------------------------------------------------------------- //

/// The initial state must include the boundary loss-sinks; routing into a missing one is a
/// referential-integrity error (Python's `KeyError`, `SimError::Reference` here), never a
/// silent drop — a silent drop would destroy mass while leaving every other case green.
#[test]
fn extinction_without_a_loss_sink_is_a_reference_error() {
    let stocks = stocks_of(vec![population(0.3, 0.5)]); // no loss-sink
    let state = state_of(&stocks);

    let err = EulerIntegrator::new(Registry::flows_only(Vec::new(), &stocks).unwrap())
        .step_report(&state, &SourceResolver::empty(), 1.0)
        .expect_err("routing into an absent loss-sink must fail");

    match err {
        SimError::Reference(msg) => assert!(
            msg.contains("loss-sink"),
            "the message names the missing sink: {msg}"
        ),
        other => panic!("expected a reference error, got {other:?}"),
    }
}
