//! Pin the Rust hex-float codec against Python-emitted conformance vectors.
//!
//! The vectors (`tests/data/hexfloat_vectors.txt`) are generated by
//! `tests/crossport/gen_vectors.py` from CPython's `float.hex()` — the single
//! source of truth. Each line is `<u64 bits> <TAB> <float.hex() string>`. We
//! assert, for every vector, both directions exactly:
//!
//! * `parse(hex_string).to_bits() == u64_bits`  — Rust reads Python's spelling
//! * `format(f64::from_bits(u64_bits)) == hex_string` — Rust writes it identically
//!
//! and the pure round-trip `parse(format(x)) == x` (bitwise). Bit-exactness, not
//! string coincidence, is the contract; the second assert is the stronger bonus
//! that our `format` reproduces CPython's canonical spelling digit-for-digit.

use simcore::hexfloat;

const VECTORS: &str = include_str!("data/hexfloat_vectors.txt");

struct Vector {
    bits: u64,
    hex: String,
}

fn vectors() -> Vec<Vector> {
    VECTORS
        .lines()
        .filter(|line| !line.trim_start().starts_with('#') && !line.trim().is_empty())
        .map(|line| {
            let (bits_str, hex) = line
                .split_once('\t')
                .unwrap_or_else(|| panic!("malformed vector line: {line:?}"));
            Vector {
                bits: u64::from_str_radix(bits_str.trim(), 16)
                    .unwrap_or_else(|_| panic!("bad bits in line: {line:?}")),
                hex: hex.trim().to_string(),
            }
        })
        .collect()
}

#[test]
fn vector_file_is_nonempty() {
    // Guards against a silently-truncated or unresolved include_str! path.
    assert!(vectors().len() >= 20, "expected the full vector set");
}

#[test]
fn parse_reproduces_python_bits() {
    for v in vectors() {
        let parsed = hexfloat::parse(&v.hex)
            .unwrap_or_else(|e| panic!("parse({:?}) failed: {e}", v.hex));
        assert_eq!(
            parsed.to_bits(),
            v.bits,
            "parse({:?}) gave bits {:016x}, expected {:016x}",
            v.hex,
            parsed.to_bits(),
            v.bits,
        );
    }
}

#[test]
fn format_reproduces_python_spelling() {
    for v in vectors() {
        let x = f64::from_bits(v.bits);
        assert_eq!(
            hexfloat::format(x),
            v.hex,
            "format(bits {:016x}) mismatch",
            v.bits,
        );
    }
}

#[test]
fn round_trip_is_bit_exact() {
    for v in vectors() {
        let x = f64::from_bits(v.bits);
        let back = hexfloat::parse(&hexfloat::format(x)).expect("round-trip parse");
        assert_eq!(back.to_bits(), v.bits, "round-trip changed bits for {:?}", v.hex);
    }
}
