//! Pin the Rust RNG port against Python-emitted conformance vectors.
//!
//! The vectors (`tests/data/rng_vectors.txt`) are generated by
//! `tests/crossport/gen_rng_vectors.py` from the frozen `simcore.rng` reference —
//! the single source of truth. Two line kinds:
//!
//! * `mix64\t0x<in>\t0x<out>` — the finalizer primitive, `u64` in → `u64` out;
//! * `draw\t0x<seed>\t<key csv>\t<step>\t0x<u64>\t<float.hex()>` — the keyed draw,
//!   both the raw `u64` and the `[0, 1)` float in its exact CPython spelling.
//!
//! This is a **Tier-1 bit-exact** gate (no tolerance): the RNG is pure `u64`
//! integer arithmetic, and `draw` is exact by construction (`x >> 11` ≤ 53 bits,
//! divisor a power of two). The float is decoded through the Step-0 hex-float
//! codec, so a mismatch surfaces as a bit difference, never rounding noise.

use simcore::hexfloat;
use simcore::rng::{self, CounterRng};

const VECTORS: &str = include_str!("data/rng_vectors.txt");

/// Parse a `0x`-prefixed lowercase `u64` hex literal.
fn parse_u64_hex(s: &str) -> u64 {
    let body = s
        .strip_prefix("0x")
        .unwrap_or_else(|| panic!("missing 0x prefix in {s:?}"));
    u64::from_str_radix(body, 16).unwrap_or_else(|_| panic!("bad u64 hex {s:?}"))
}

/// Parse the key field: comma-separated `u64`s, empty string for the `()` key.
fn parse_key(field: &str) -> Vec<u64> {
    if field.is_empty() {
        Vec::new()
    } else {
        field
            .split(',')
            .map(|w| w.parse::<u64>().unwrap_or_else(|_| panic!("bad key word {w:?}")))
            .collect()
    }
}

fn data_lines() -> impl Iterator<Item = &'static str> {
    VECTORS
        .lines()
        .filter(|line| !line.trim_start().starts_with('#') && !line.trim().is_empty())
}

#[test]
fn vector_file_is_nonempty() {
    // Guards against a silently-truncated or unresolved include_str! path.
    let n = data_lines().count();
    assert!(n >= 50, "expected the full RNG vector set, got {n}");
}

#[test]
fn mix64_vectors_match() {
    let mut checked = 0;
    for line in data_lines() {
        let mut fields = line.split('\t');
        if fields.next() != Some("mix64") {
            continue;
        }
        let input = parse_u64_hex(fields.next().expect("mix64 input"));
        let expected = parse_u64_hex(fields.next().expect("mix64 output"));
        assert_eq!(
            rng::mix64(input),
            expected,
            "mix64(0x{input:016x}) mismatch",
        );
        checked += 1;
    }
    assert!(checked >= 10, "expected the mix64 vectors, checked {checked}");
}

#[test]
fn draw_vectors_match() {
    let mut checked = 0;
    for line in data_lines() {
        let mut fields = line.split('\t');
        if fields.next() != Some("draw") {
            continue;
        }
        let seed = parse_u64_hex(fields.next().expect("seed"));
        let key = parse_key(fields.next().expect("key"));
        let step: u64 = fields.next().expect("step").parse().expect("step decimal");
        let want_u64 = parse_u64_hex(fields.next().expect("draw_u64"));
        let want_fhex = fields.next().expect("float hex");

        let g = CounterRng::new(seed);

        assert_eq!(
            g.draw_u64(&key, step),
            want_u64,
            "draw_u64(seed=0x{seed:x}, key={key:?}, step={step}) mismatch",
        );
        // Bit-exact float: format the draw through the hex-float codec and compare
        // the exact CPython spelling. keyed_hash is exercised via draw_u64 above.
        assert_eq!(
            hexfloat::format(g.draw(&key, step)),
            want_fhex,
            "draw(seed=0x{seed:x}, key={key:?}, step={step}) float mismatch",
        );
        checked += 1;
    }
    assert!(checked >= 50, "expected the draw vectors, checked {checked}");
}
