//! Dump the **biosphere** port's own completeness inventory as JSON — slice 3 of the
//! reference flip (`docs/plans/post-roadmap-reference-flip.md`).
//!
//! The union of `Flow::type_name()` / `AuxProcess::type_name()` over the four canonical
//! biosphere builds, which is exactly what `tests/test_freeze_manifest.py::_flow_set()` /
//! `_aux_set()` derive on the Python side (`type(flow).__name__` over the same four
//! registries). `tests/crossport/test_inventory_parity.py` asserts this output equals
//! `docs/biosphere-reference.manifest.json`.
//!
//! ⚠ **Derived, never hand-listed — and that is the whole point of the program.** No
//! roster of names appears here: the sets come from walking the built registries, so a
//! flow added to a compartment builder but wired into no golden still shows up. A version
//! of this file that printed a literal list would pass the gate while proving nothing.
//!
//! ⚠⚠ **`param_files` is deliberately ABSENT, and it is not an oversight.** The manifest's
//! third axis names the frozen `params/*.yaml` files, and **this port has no referent for
//! it**: Rust reads no YAML. It reads `src/biosphere/biosphere_params.txt`, a file
//! *generated by Python* (`tests/crossport/gen_biosphere_params.py`) whose `photo.` /
//! `pheno.` / `vern.` prefixes are the generator's naming, not filenames — three of them
//! come out of the single `phenology.yaml`, and the sibling/station equivalents carry no
//! prefix at all. Anything this program printed under that key would be a copy of the
//! Python list travelling through Rust, so the "parity" gate would be Python against
//! Python. The gate asserts the key set to keep that from being added by accident.

use domains::biosphere::system::{
    build_season, consumer_chamber_scenario, perennial_chamber_scenario, sealed_chamber_scenario,
    SeasonScenario, DEFAULT_SCENARIO,
};
use std::collections::BTreeSet;

/// The four canonical builds — the same union the Python manifest is derived from
/// (`_canonical_registries()`): the open field carries the boundary-atmosphere producer
/// flows, the sealed chambers add the decomposer / water-cycle / consumer ones.
fn canonical() -> Vec<SeasonScenario> {
    vec![
        DEFAULT_SCENARIO,
        sealed_chamber_scenario(),
        perennial_chamber_scenario(),
        consumer_chamber_scenario(),
    ]
}

fn json_array(names: &BTreeSet<&str>) -> String {
    let items: Vec<String> = names.iter().map(|n| format!("\"{n}\"")).collect();
    format!("[{}]", items.join(", "))
}

fn main() {
    let mut flows: BTreeSet<&str> = BTreeSet::new();
    let mut aux: BTreeSet<&str> = BTreeSet::new();
    for scenario in canonical() {
        let (_, registry) = build_season(&scenario).expect("canonical biosphere build");
        flows.extend(registry.flows().iter().map(|f| f.type_name()));
        aux.extend(registry.aux_processes().iter().map(|a| a.type_name()));
    }

    // Tier-0 sanity on the program itself: an inventory that came back empty would
    // compare against a non-empty manifest and fail loudly, but failing *here* names the
    // cause (a build that wired nothing) instead of reporting 23 missing flows.
    assert!(
        !flows.is_empty(),
        "canonical biosphere builds wired no flows"
    );
    assert!(
        !aux.is_empty(),
        "canonical biosphere builds wired no aux processes"
    );

    println!("{{");
    println!("  \"aux_set\": {},", json_array(&aux));
    println!("  \"flow_set\": {}", json_array(&flows));
    println!("}}");
}
