"""Generate the RNG cross-port conformance vectors the Rust port is pinned against.

The reference generator is the frozen ``simcore.rng`` (``mix64`` / ``keyed_hash`` /
``CounterRng``). Rust's port must reproduce every line bit-for-bit: ``draw_u64`` as
an exact ``u64`` and ``draw`` as the exact ``float.hex()`` spelling (decoded through
the Step-0 hex-float codec).

Two vector kinds, one file:

* ``mix64`` lines — the finalizer primitive on its own (``u64`` in → ``u64`` out),
  including the published splitmix64(seed=0) grounding inputs;
* ``draw`` lines — ``(seed, key, step) → (draw_u64, draw().hex())``.

**Single source of truth.** This script is the only writer of ``rng_vectors.txt``.
``test_crossport.py`` (1) checks the committed file stays in sync with ``render()``
and (2) *anchors* its fixed rows to the hand-pinned known-answer vectors in
``tests/test_rng.py`` (``_GOLDEN`` / ``_SPLITMIX64_SEED0``), which are grounded
against published splitmix64 output. So the generated file is externally anchored,
not self-referential: Rust == file == Python, and Python == published.

The grid (below) is what justifies the generated-file machinery over hand-inlining:
the ~9 fixed known-answer constants alone could be transcribed, but a broad
seed×key×step grid cannot — and breadth is where a subtle fold-order or masking bug
would surface.

Coverage note: Python's ``mix64`` masks a wider-than-64-bit input internally; Rust's
``u64`` makes such an input impossible to express, so — like the ported-away
``TypeError`` guards — that case is subsumed by the type system and no vector emits
it. Every mix64 input here is already ≤64 bits.

Regenerate with::

    uv run python tests/crossport/gen_rng_vectors.py
"""

from __future__ import annotations

from pathlib import Path

from simcore.rng import CounterRng, keyed_hash, mix64

_MASK64 = 0xFFFFFFFFFFFFFFFF
_GAMMA = 0x9E3779B97F4A7C15

# The committed vector file the Rust integration test reads.
VECTORS_PATH = (
    Path(__file__).resolve().parents[2]
    / "rust"
    / "crates"
    / "simcore"
    / "tests"
    / "data"
    / "rng_vectors.txt"
)

# The six fixed draw inputs from tests/test_rng.py::_GOLDEN — the anchor set the
# reconciliation test binds to the hand-pinned known answers. Kept in the same order.
_FIXED_DRAWS: tuple[tuple[int, tuple[int, ...], int], ...] = (
    (0x0, (), 0),
    (0x0, (1,), 0),
    (0x0, (1,), 1),
    (0x0, (2,), 0),
    (0x3039, (7, 99), 42),
    (0xDEADBEEF, (3,), 1000000),
)


def _mix64_inputs() -> list[int]:
    """mix64 inputs: the published splitmix64(seed=0) grounding cases first, then a
    spread of edges. All ≤64 bits (order preserved, duplicates removed)."""
    published = [(i * _GAMMA) & _MASK64 for i in (1, 2, 3)]
    edges = [
        0x0,
        0x1,
        _MASK64,
        _GAMMA,
        1 << 63,
        0x0123456789ABCDEF,
        0x1234,
        0xFEDCBA9876543210,
    ]
    seen: set[int] = set()
    ordered: list[int] = []
    for z in [*published, *edges]:
        if z not in seen:
            seen.add(z)
            ordered.append(z)
    return ordered


def _draw_cases() -> list[tuple[int, tuple[int, ...], int]]:
    """The fixed anchor rows first, then a seed×key×step grid for breadth."""
    seeds = (0x0, 0x3039, 0xDEADBEEF)
    keys: tuple[tuple[int, ...], ...] = ((), (0,), (1,), (2,), (7, 99), (1, 2, 3))
    steps = (0, 1, 42, 1000000)
    cases: list[tuple[int, tuple[int, ...], int]] = list(_FIXED_DRAWS)
    for seed in seeds:
        for key in keys:
            for step in steps:
                cases.append((seed, key, step))
    seen: set[tuple[int, tuple[int, ...], int]] = set()
    ordered: list[tuple[int, tuple[int, ...], int]] = []
    for c in cases:
        if c not in seen:
            seen.add(c)
            ordered.append(c)
    return ordered


def render() -> str:
    """The exact text of the committed vector file (LF newlines)."""
    lines = [
        "# RNG cross-port conformance vectors — "
        "GENERATED by tests/crossport/gen_rng_vectors.py",
        "# mix64 lines:  mix64 <TAB> 0x<input u64> <TAB> 0x<output u64>",
        "# draw lines:   draw <TAB> 0x<seed> <TAB> <key: comma-separated ints, "
        "empty for ()> <TAB> <step decimal> <TAB> 0x<draw_u64> <TAB> "
        "<draw() float.hex()>",
    ]
    for z in _mix64_inputs():
        lines.append(f"mix64\t0x{z:x}\t0x{mix64(z):x}")
    for seed, key, step in _draw_cases():
        rng = CounterRng(seed)
        u64 = rng.draw_u64(key, step)
        # keyed_hash and draw_u64 must agree — belt and suspenders on the reference.
        assert u64 == keyed_hash(seed, key, step)
        fhex = rng.draw(key, step).hex()
        keycsv = ",".join(str(w) for w in key)
        lines.append(f"draw\t0x{seed:x}\t{keycsv}\t{step}\t0x{u64:x}\t{fhex}")
    return "\n".join(lines) + "\n"


def main() -> int:
    VECTORS_PATH.parent.mkdir(parents=True, exist_ok=True)
    VECTORS_PATH.write_text(render(), encoding="utf-8", newline="\n")
    n_mix = len(_mix64_inputs())
    n_draw = len(_draw_cases())
    print(f"wrote {n_mix} mix64 + {n_draw} draw vectors to {VECTORS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
