"""Generate the hex-float conformance vectors the Rust codec is pinned against.

The vectors are `(u64 bit pattern, Python ``float.hex()`` string)` pairs. Rust's
`hexfloat::parse` must reproduce the exact bits from the string, and its
`hexfloat::format` must reproduce the exact string from the bits — so the Python
reference (CPython's `float.hex`/`float.fromhex`) is the single source of truth,
emitted here and consumed by `rust/crates/simcore/tests/hexfloat_roundtrip.rs`.

The committed file is checked in sync by `test_crossport.py`; regenerate with::

    uv run python tests/crossport/gen_vectors.py

Coverage is the schema's exact forms plus the edges a hand-rolled codec breaks on:
``±0.0``, min/max subnormal, min/max normal, and the real ``crew_state`` amounts.
"""

from __future__ import annotations

import struct
from pathlib import Path

# The committed vector file the Rust round-trip test reads.
VECTORS_PATH = (
    Path(__file__).resolve().parents[2]
    / "rust"
    / "crates"
    / "simcore"
    / "tests"
    / "data"
    / "hexfloat_vectors.txt"
)

# The crew_state golden amounts (a live golden the codec must handle), plus the
# extinction_threshold 0.0 that appears on every stock.
_CREW_AMOUNTS: tuple[float, ...] = (
    float.fromhex("0x1.87e90ff972484p+3"),
    float.fromhex("0x1.2e66666666677p+9"),
    float.fromhex("0x1.1efa43fe5c91fp+8"),
    float.fromhex("0x1.ed844d013a90bp+3"),
    float.fromhex("0x1.79652bd3c3604p+2"),
    float.fromhex("0x1.5cccccccccd10p+9"),
    float.fromhex("0x1.5cccccccccd10p+10"),
    float.fromhex("0x1.4ed916872b068p+5"),
)


def sample_values() -> list[float]:
    """The ordered list of doubles to pin (duplicates removed, order preserved)."""
    values: list[float] = [
        0.0,
        -0.0,
        1.0,
        -1.0,
        2.0,
        0.5,
        1.5,
        3.0,
        0.1,
        -0.1,
        3.141592653589793,  # math.pi
        2.718281828459045,  # math.e
        5e-324,  # min positive subnormal
        -5e-324,
        struct.unpack("<d", struct.pack("<Q", 0x000F_FFFF_FFFF_FFFF))[
            0
        ],  # max subnormal
        struct.unpack("<d", struct.pack("<Q", 0x0010_0000_0000_0000))[0],  # min normal
        struct.unpack("<d", struct.pack("<Q", 0x7FEF_FFFF_FFFF_FFFF))[0],  # max normal
        1.0 / 3.0,
        1e308,
        1e-308,
        123456789.0,
        -987654321.123,
        *_CREW_AMOUNTS,
    ]
    seen: set[int] = set()
    unique: list[float] = []
    for v in values:
        bits = struct.unpack("<Q", struct.pack("<d", v))[0]
        if bits not in seen:
            seen.add(bits)
            unique.append(v)
    return unique


def render() -> str:
    """The exact text of the committed vector file (LF newlines)."""
    lines = [
        "# hex-float conformance vectors — GENERATED by tests/crossport/gen_vectors.py",
        "# format: <u64 bits, 16 lowercase hex> <TAB> <Python float.hex() string>",
        "# The Rust codec must round-trip both directions exactly against these.",
    ]
    for v in sample_values():
        bits = struct.unpack("<Q", struct.pack("<d", v))[0]
        lines.append(f"{bits:016x}\t{v.hex()}")
    return "\n".join(lines) + "\n"


def main() -> int:
    VECTORS_PATH.parent.mkdir(parents=True, exist_ok=True)
    VECTORS_PATH.write_text(render(), encoding="utf-8", newline="\n")
    print(f"wrote {len(sample_values())} vectors to {VECTORS_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
