"""Reference flip: the Rust tree's own inventory vs. the frozen manifests.

⚠⚠ **BOTH CASES ARE NOW STALENESS CHECKS, AND THAT IS THE FIRST THING TO KNOW BEFORE
READING A FAILURE.** Slice 3 built both as *parity* checks with two independent origins.
Slice 6 re-anchored the **biosphere** manifest to the Rust tree and slice 7 the
**station** one, so for both:

* **a STALENESS check.** The manifest is generated from the same derivations this dump
  prints — since slice C7 the biosphere's is written by the reference itself, the
  station's still by the checker — so a disagreement no longer means "the
  ports differ" — it means **the committed manifest is out of date with the reference
  tree**, i.e. something was added to the reference and never frozen. That is the
  completeness axis, re-homed to the side that now owns it. Python's conformance to the
  same sets is checked separately and cargo-free, in `tests/test_freeze_manifest.py` and
  `tests/test_station_freeze_manifest.py`.

**Why these are still worth running, and are not round trips.** Each compares the
*committed artifact* against a *freshly built tree* — the same relationship the Python
completeness gates always had, on the other side. What they can no longer do is
arbitrate between the ports; that authority went with the flip.

⚠ **The station's failure advice keeps its own paragraph, and it matters MORE now, not
less.** The dump's registry selection is five hand-mirrored judgement calls
(`dump_station_inventory.rs` lists them), and after slice 7 a mis-mirrored one is
**written into the frozen manifest** by a regeneration rather than merely reported as a
mismatch. So the first question on a station failure is still "is the selection right?",
though the second changed from "which port is wrong?" to "what moved in the reference,
and was it meant to?".

⚠⚠ **The manifests' third axis, `param_files`, IS compared — since slice C8, and for
three slices before that it deliberately was not.** The reversal is kept in full,
because the old reason was correct for its day and the new one is narrower than it
looks.

*Until C1:* the port read no YAML at all. It read `biosphere_params.txt` /
`sibling_params.txt` / `station_params.txt`, all three **generated by Python**
(`tests/crossport/gen_*_params.py`) from the frozen loaders, as flat `name → hexfloat`
lines whose prefixes were the generator's naming and not filenames — `photo.` against
`photosynthesis.yaml`, three prefixes out of the single `phenology.yaml`, 17 loaders
against 15 frozen files, and no prefix at all on the sibling/station side. Anything Rust
printed under that key would have been the Python list travelling out and back, so the
gate would have compared Python against Python: the self-referential shape this repo had
to dissolve once already, for the RNG vectors.

*Since C1 and C8:* the reference loads the YAML itself and produces the census and the
digest, so the key has a referent. ⚠ **But what re-anchored is the census RULE and the
normalization RULE, not the numbers** — the 23 digits are author-neutral by
construction, because both sides hash the same file the same way. So what this
comparison actually watches is the **roster**: a param file the reference stopped
loading, or one added and
wired into no loader. It is compared as a whole mapping rather than as a key set, which
is what additionally catches an *edited* param file whose manifest entry was never
regenerated — the desync slice 5 measured, on the param axis.

⚠ **The authoring contract joined in slice 8, and it is a THIRD kind of case.** Its
surface is the author-facing *platform* (grammar, VM node/op set, file schema, flow-type
registry), which has no built registry to walk — so unlike the two above, the reference
side cannot enumerate it at runtime and every axis is part derived, part hand-maintained
roster. `authoring::surface`'s module docs and that manifest's `_authority` block say
which is which per key. The staleness check is the same in shape and weaker in evidence,
and it is written down here so nobody reads a green authoring row as the station row's
equal.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs"
RUST_DOMAINS_DIR = REPO_ROOT / "rust" / "crates" / "domains"
RUST_STATION_DIR = REPO_ROOT / "rust" / "crates" / "station"
RUST_AUTHORING_DIR = REPO_ROOT / "rust" / "crates" / "authoring"

# The set-valued axes compared straight across, per case. ⚠ The dump's *exact* key set
# is asserted too (`_DUMP_KEYS`), not read as a filter: adding a key to a dump program
# turns this gate red until whoever did it has classified it in the manifest's
# `_AUTHORITY`. A filter would have let a tautology in silently.
#
# ⚠⚠ That forcing function did its job and THEN the answer changed. Until slice C8 this
# comment named `param_files` as the example of a key that could not be an axis, because
# the port read no YAML — only a table Python generated from the Python loaders, so
# anything it printed would have been that list travelling out and back. Slice C1 gave
# the reference the YAML loaders and C8 the census + digest, so the key has a referent
# now. The forcing function is what made the change deliberate rather than quiet: adding
# the key reddened this gate before anything was regenerated.
_COMPARED_AXES = frozenset({"flow_set", "aux_set"})

#: The mapping-valued axes compared key-by-key rather than as sets (slice C8).
#:
#: ⚠ `param_files` is `filename -> newline-normalized sha-256`. Its **values** are
#: author-neutral — both sides digest the same file, which is why re-anchoring moved not
#: one of the 23 hashes — so what this watches is the **roster**: a param file the
#: reference stopped loading, or one added and wired into no loader. Compared as a
#: whole mapping rather than a key set, so a changed digest is red too — which is what
#: catches an *edited* param file whose manifest entry was never regenerated.
_COMPARED_MAPPINGS = frozenset({"param_files"})

#: The science-gate census axes (slice C4). A third comparison shape, and it is not
#: pedantry that it is not folded into `_COMPARED_MAPPINGS`: the manifest gives EVERY
#: roster scenario a key — an explicitly empty list where no gate exists, which says
#: "measured, none" as opposed to saying nothing — while the dump emits only the
#: scenarios that actually carry a claim, because the roster is the manifest's own hand
#: authority and not the reference's. So the comparison drops the empty entries from the
#: frozen side and then demands EXACT equality in both directions: a Rust gate the
#: manifest lacks is an unregenerated re-anchoring, and a manifest claim no Rust gate
#: produces is a frozen band whose assertion has been deleted — the precise failure
#: `science_bands` was added to make impossible.
_COMPARED_CENSUS = frozenset({"science_bands", "liveness_floors"})

# (label, crate dir, example, manifest, dump keys). One per manifest that carries a
# registry-derived inventory; the biosphere is delegated out of the station manifest, so
# the two sets are disjoint by contract and each is checked against its own file. ⚠ The
# biosphere dump grew in slice 6 — it now emits everything the manifest sources from the
# reference tree, plus `locked_dt_days`, which is emitted to be CHECKED and never
# spliced (see `test_the_locked_dt_matches_the_reference_tree`). ⚠ The station dump grew
# in slice 7, by its two sealed horizons only: that contract has no structured dt key to
# check a `locked_dt` against, and slice 7 declined to add one (widening the frozen
# surface is its own unfreeze) — see the `numerics_note` entry in that manifest.
#: ⚠ `weather_sha256` joined in slice C9 — the second checked-never-spliced key, see
#: `test_the_weather_hash_matches_the_reference_tree`.
#: ⚠⚠ `science_bands` / `liveness_floors` joined in slice C4 — the science-gate
#: census, which until then had no Rust referent and was the largest Python-authored
#: block of any contract. They are compared by `_COMPARED_CENSUS` below, which needs its
#: own comparison shape: the value is `scenario -> [claim]` and the manifest carries
#: roster keys the dump deliberately does not emit.
_BIOSPHERE_DUMP_KEYS = frozenset(
    {
        "flow_set",
        "aux_set",
        "horizons",
        "light_path_samples",
        "liveness_floors",
        "locked_dt_days",
        "param_files",
        "science_bands",
        "weather_sha256",
    }
)
#: ⚠ `science_bands` / `liveness_floors` joined in **slice C4b**, the follow-on C4
#: scheduled: the two claims this contract carries needed `station` types, so they
#: live in a second table (`rust/crates/station/src/science_gates.rs`) invoking the
#: same exported macro. Both dumps carry a census from here on.
_STATION_DUMP_KEYS = frozenset(
    {
        "flow_set",
        "aux_set",
        "horizons",
        "liveness_floors",
        "param_files",
        "science_bands",
    }
)
#: ⚠ The authoring dump (slice 8) has NO axis in common with the two above — the
#: platform contract freezes a grammar, a file schema and a flow-type registry, not a
#: wired inventory — so it gets its own gate below rather than a row in `_CASES`. Every
#: key it emits is written into the manifest by that same program (slice C7), so the
#: whole set is compared.
_AUTHORING_DUMP_KEYS = frozenset(
    {
        "binary_ops",
        "expr_nodes",
        "flow_types",
        "integrator_names",
        "param_loaders",
        "rate_classes",
        "ref_keywords",
        "schema_fields",
        "step_token",
    }
)
_CASES = [
    (
        "biosphere",
        RUST_DOMAINS_DIR,
        "dump_biosphere_inventory",
        "biosphere-reference.manifest.json",
        _BIOSPHERE_DUMP_KEYS,
    ),
    (
        "station",
        RUST_STATION_DIR,
        "dump_station_inventory",
        "station-reference.manifest.json",
        _STATION_DUMP_KEYS,
    ),
]


def _rust_inventory(crate_dir: Path, example: str) -> dict:
    """Run an inventory dump example and parse its JSON stdout."""
    # ⚠⚠ `encoding="utf-8"`, and it is NOT boilerplate. `text=True` alone decodes
    # the pipe with `locale.getpreferredencoding()` — cp1252 on the Windows dev box —
    # and every byte this program emitted was ASCII (names, hex floats, sha-256
    # digests) until slice C4, so the pipe's encoding had never mattered. The science
    # census is the first non-ASCII key: it carries `—`, `⚠`, `Γ` and `CO₂` inside
    # frozen claim text. Without this the first regeneration wrote mojibake
    # (`—` -> `â€”`) INTO the frozen contract, and nothing was red — the manifest and
    # the checker agreed, because the corruption happened on the way in. It was
    # caught by predicting the diff before regenerating, which is the only reason it
    # is a note here instead of a committed contract.
    proc = subprocess.run(
        ["cargo", "run", "-q", "--example", example],
        cwd=crate_dir,
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    assert proc.returncode == 0, f"cargo run {example} failed:\n{proc.stderr}"
    return json.loads(proc.stdout)


@pytest.mark.skipif(shutil.which("cargo") is None, reason="cargo not installed")
@pytest.mark.parametrize("label,crate_dir,example,manifest_name,dump_keys", _CASES)
def test_rust_inventory_equals_the_frozen_manifest(
    label: str, crate_dir: Path, example: str, manifest_name: str, dump_keys: frozenset
) -> None:
    """Rust's derived flow/aux inventory equals the committed manifest's, set for set.

    Runs wherever `cargo` is on PATH, and on the `crossport` CI job — which invokes
    `uv run pytest tests/crossport/` on the **directory**, so a new file here is
    collected rather than needing to be listed. (Checked, not inherited: this repo has
    two recorded green-by-skip incidents.)
    """
    manifest = json.loads((DOCS_DIR / manifest_name).read_text(encoding="utf-8"))
    dump = _rust_inventory(crate_dir, example)

    assert set(dump) == dump_keys, (
        f"{example} dumps {sorted(dump)}, not {sorted(dump_keys)} — see this "
        f"module's docstring before adding an axis. A new key must be classified in "
        f"the manifest's `_AUTHORITY` and must be something the reference can "
        f"honestly produce: a key whose value is really the checker's own list "
        f"travelling out and back makes this gate compare Python against Python."
    )

    # ⚠ Guard the comparison itself, not just its result. An equality against an empty
    # frozen list is a green test that has checked nothing, and the flow axis is where
    # this gate's teeth are. (The *aux* axis is legitimately empty on the station side —
    # see `test_the_station_aux_axis_is_empty_by_delegation`, which states that rather
    # than letting `[] == []` pass as evidence.)
    assert manifest["flow_set"], f"{manifest_name} freezes no flows — nothing compared"

    # ⚠ The advice still branches, and the reason changed rather than went away. Both
    # cases are staleness now (slices 6 and 7), so the shared half is one message — but
    # the station's dump mirrors five registry-selection judgement calls by hand, and a
    # mis-mirrored one reads exactly like a reference move while being neither. That
    # question has to be asked FIRST on this case and is meaningless on the other, and
    # after slice 7 a wrong answer to it gets *written into* the frozen manifest by the
    # regeneration this message sends you to. Kept per slice 5's lesson that no test
    # catches a correct assertion giving wrong advice.
    biosphere = manifest_name.startswith("biosphere")
    ceremony = (
        "docs/biosphere-reference.md" if biosphere else "docs/station-reference.md"
    )
    # ⚠ The two contracts regenerate differently since slice C7, and the branch is the
    # slice's own progress showing through: the biosphere manifest is written by the
    # reference, the station's is still written by the checker. When the station writer
    # lands this collapses back to one string — and until it does, printing the wrong
    # command is exactly the "correct assertion, wrong advice" failure slice 5 recorded.
    regen = (
        "cd rust && cargo run --example dump_biosphere_inventory -- --write-manifest"
        if biosphere
        else "uv run python tests/test_station_freeze_manifest.py"
    )
    selection = (
        ""
        if biosphere
        else (
            "⚠ FIRST, before reading this as a reference move at all: check the "
            "registry SELECTION in the dump example against the Python gate's "
            "`_station_registries()`. A mis-mirrored build option (self-discharge, "
            "with_harvest, the fast-vs-slow registry index) reads exactly like a "
            "reference change and is not one — and since slice 7 regenerating would "
            "write it into the frozen manifest. Only if the selection is right:\n"
        )
    )
    advice = (
        f"{selection}⚠ This manifest is generated FROM this dump, so this is NOT a "
        "port-vs-port divergence: the reference tree has changed and the committed "
        f"manifest has not been regenerated. That is an unfreeze — follow the ceremony "
        f"in {ceremony}, then `{regen}`. If you did not mean to change "
        "the frozen surface, the finding is whatever added or removed the name."
    )
    for axis in sorted(_COMPARED_AXES):
        assert dump[axis] == manifest[axis], (
            f"{label} {axis} diverges between the Rust tree and {manifest_name}:\n"
            f"  only in Rust:     {sorted(set(dump[axis]) - set(manifest[axis]))}\n"
            f"  only in manifest: {sorted(set(manifest[axis]) - set(dump[axis]))}\n"
            f"{advice}"
        )

    # ⚠ The mapping axes report the ROSTER difference and the CHANGED-VALUE difference
    # separately, because they are different findings with different first questions: a
    # name only in Rust is a loader added, a name only in the manifest is a loader
    # dropped, and a name in both with a different digest is a param FILE edited without
    # the ceremony.
    #
    # ⚠⚠ This loop is here because TWO NEGATIVE CONTROLS FOUND IT MISSING. Slice C8's
    # first draft added `_COMPARED_MAPPINGS` and no consumer for it — a constant that
    # read exactly like coverage. `test_the_dump_key_sets_are_the_ones_the_generators_
    # consume` stayed green (it checks key sets, not comparisons), ruff does not flag an
    # unused module-level name, and the suite was green. What said so was editing a
    # param file without regenerating, and removing newline normalization from the
    # reference: both left this gate **passing**. *A roster with no consumer is the
    # `docs/log/reference-flip.md` slice-8 lesson exactly — a control with no test to
    # redden IS the finding — and here the control had to be run to see it.*
    for axis in sorted(_COMPARED_MAPPINGS):
        assert axis in manifest, f"{manifest_name} has no {axis} to compare"
        rust, frozen = dump[axis], manifest[axis]
        changed = sorted(k for k in set(rust) & set(frozen) if rust[k] != frozen[k])
        assert rust == frozen, (
            f"{label} {axis} diverges between the Rust tree and {manifest_name}:\n"
            f"  only in Rust (loaded, not frozen):     "
            f"{sorted(set(rust) - set(frozen))}\n"
            f"  only in manifest (frozen, not loaded): "
            f"{sorted(set(frozen) - set(rust))}\n"
            f"  same name, different digest:           {changed}\n"
            f"{advice}"
        )
        # ⚠ And guard the comparison, not just its result: an empty mapping on both
        # sides is a green test that has checked nothing.
        assert frozen, f"{manifest_name} freezes no {axis} — nothing compared"

    # ⚠ The census axes. Written with an `axis in dump` guard while only the biosphere
    # carried a Rust-authored census, so that C4b would start comparing the station's
    # without this file being edited. C4b landed and the guard was REMOVED rather than
    # left: with both dumps carrying a census it can never fire, and a `continue` that
    # cannot fire is a `continue` that silently skips the comparison the day a dump
    # stops emitting one. That case is not unguarded — `set(dump) == dump_keys` above
    # reddens on a missing key — so the guard bought nothing and could only hide.
    for axis in sorted(_COMPARED_CENSUS):
        assert axis in dump, f"{label} dump emits no {axis} to compare"
        frozen_nonempty = {k: v for k, v in manifest[axis].items() if v}
        assert frozen_nonempty, f"{manifest_name} freezes no {axis} — nothing compared"
        changed = sorted(
            k
            for k in set(dump[axis]) & set(frozen_nonempty)
            if dump[axis][k] != frozen_nonempty[k]
        )
        assert dump[axis] == frozen_nonempty, (
            f"{label} {axis} diverges between the Rust tree and {manifest_name}:\n"
            f"  only in Rust (declared, not frozen):     "
            f"{sorted(set(dump[axis]) - set(frozen_nonempty))}\n"
            f"  only in manifest (frozen, not declared): "
            f"{sorted(set(frozen_nonempty) - set(dump[axis]))}\n"
            f"  same scenario, different claims:         {changed}\n"
            f"{advice}"
        )


@pytest.mark.skipif(shutil.which("cargo") is None, reason="cargo not installed")
def test_the_frozen_biosphere_manifest_is_not_stale() -> None:
    """Every biosphere key sourced from the reference tree still reads what it emits.

    The set axes are covered above; this is the rest of what slice 6 re-anchored — the
    horizons and the light-path fingerprint — so a reference-side change to any of them
    is red rather than a manifest quietly describing a tree that has moved on.

    ⚠ The fingerprint is hashed here rather than compared sample by sample, because the
    hash is what the manifest stores and hashing is the one step the Rust side does not
    do (that crate carries no digest dependency). The samples themselves are exact
    hex-float text, so this is an exact comparison, not a tolerance.
    """
    manifest = json.loads(
        (DOCS_DIR / "biosphere-reference.manifest.json").read_text(encoding="utf-8")
    )
    dump = _rust_inventory(RUST_DOMAINS_DIR, "dump_biosphere_inventory")

    fingerprint = hashlib.sha256(
        "|".join(dump["light_path_samples"]).encode("utf-8")
    ).hexdigest()
    assert manifest["forcing"]["light_path"] == fingerprint, (
        "the reference tree's within-day PAR shape has moved and the manifest still "
        "pins the old fingerprint — an unfreeze, not a diff to accept"
    )
    assert dump["light_path_samples"], "no samples compared"

    assert manifest["long_horizon_years"] == dump["horizons"]["long_horizon_years"]
    frozen_years = {
        name: entry["years"] for name, entry in manifest["scenarios"].items()
    }
    for key, years in dump["horizons"].items():
        assert years in frozen_years.values(), (
            f"the reference tree's {key} = {years} appears in no frozen scenario: "
            f"{frozen_years}"
        )


@pytest.mark.skipif(shutil.which("cargo") is None, reason="cargo not installed")
def test_the_locked_dt_matches_the_reference_tree() -> None:
    """The anti-derived literal gets the half it was missing.

    ⚠ `dt_days` is **deliberately** a hand-written literal in the manifest and a second
    hand-written literal in the Python gate — a contract field that imports its own
    value auto-follows the code, and the 2026-08-14 step move became a deliberate
    ceremony only because that literal went red. Slice 6 does not touch that. What it
    adds is the check that never existed: the frozen literal against the **reference
    tree's** `BIO_DT`. So moving Rust's step now turns something red at once,
    instead of surfacing later as
    "every golden moved".

    ⚠ Deliberately NOT extended to `integrator`. There is no importable scheme name on
    either side — each run helper selects it inline — so the only way to write this pair
    symmetrically would be to type `"EulerIntegrator"` into the Rust dump and compare it
    to the manifest's copy: two hand-written literals checked against each other, which
    reads like a gate and is none. The integrator stays enforced by the goldens.
    """
    manifest = json.loads(
        (DOCS_DIR / "biosphere-reference.manifest.json").read_text(encoding="utf-8")
    )
    dump = _rust_inventory(RUST_DOMAINS_DIR, "dump_biosphere_inventory")
    assert manifest["dt_days"] == dump["locked_dt_days"], (
        f"the reference tree runs the biosphere at dt = {dump['locked_dt_days']}, but "
        f"the frozen manifest declares {manifest['dt_days']}. Moving the step is an "
        "unfreeze (docs/biosphere-reference.md) — the literal is hand-written so that "
        "this is a ceremony rather than a silent follow."
    )


@pytest.mark.skipif(shutil.which("cargo") is None, reason="cargo not installed")
def test_the_weather_hash_matches_the_reference_tree() -> None:
    """The two sides read the same weather bytes — slice C9's half of the forcing hash.

    ⚠ **This is the gate that keeps a reach-out `include_str!` honest.** Since C9 the
    reference reads `tests/oracle/winter_wheat_weather.json` directly, embedding it at
    compile time from a path that climbs out of the Rust tree into the Python one. The
    checker reads the same file from disk. Nothing else in the suite would notice if
    those two stopped being the same file — and they are *scheduled* to be disturbed:
    the relocation slice moves this fixture out of `tests/`, and a move that updates one
    side's path and not the other's would otherwise leave a stale copy driving one side
    with a green suite.

    ⚠ The manifest value itself stays Python-authored, deliberately; the reasoning is in
    `_AUTHORITY["forcing/weather_sha256"]`. This is the `locked_dt_days` pattern — the
    reference emits a value to be *checked*, not to be spliced.
    """
    manifest = json.loads(
        (DOCS_DIR / "biosphere-reference.manifest.json").read_text(encoding="utf-8")
    )
    dump = _rust_inventory(RUST_DOMAINS_DIR, "dump_biosphere_inventory")
    assert manifest["forcing"]["weather_sha256"] == dump["weather_sha256"], (
        "the weather fixture the reference COMPILED IN hashes to "
        f"{dump['weather_sha256']}, but the manifest records "
        f"{manifest['forcing']['weather_sha256']} for the file on disk. Either the "
        "fixture moved on one side only, or it was edited without the unfreeze "
        "ceremony in docs/biosphere-reference.md."
    )


@pytest.mark.skipif(shutil.which("cargo") is None, reason="cargo not installed")
def test_the_frozen_station_manifest_is_not_stale() -> None:
    """Every station key sourced from the reference tree still reads what it emits.

    The set axes are covered above; this is the rest of what slice 7 re-anchored — the
    two sealed horizons — so a reference-side change to either is red rather than a
    manifest quietly describing a tree that has moved on.

    ⚠ `sealed_energy_years` is `LONG_HORIZON_YEARS` in the reference tree, the same
    constant the biosphere manifest freezes as `long_horizon_years`. Moving it is one
    reference-side edit that turns **both** contracts stale, and this is one of the two
    places that says so.
    """
    manifest = json.loads(
        (DOCS_DIR / "station-reference.manifest.json").read_text(encoding="utf-8")
    )
    dump = _rust_inventory(RUST_STATION_DIR, "dump_station_inventory")

    for key, years in dump["horizons"].items():
        assert manifest[key] == years, (
            f"the reference tree runs {key} = {years}, but the frozen manifest "
            f"declares {manifest[key]}. Moving a sealed horizon is an unfreeze "
            "(docs/station-reference.md) — regenerate the manifest as its record, and "
            "note that sealed_energy_years is shared with the biosphere contract."
        )
    assert dump["horizons"], "no horizons compared"


@pytest.mark.skipif(shutil.which("cargo") is None, reason="cargo not installed")
def test_the_frozen_authoring_manifest_is_not_stale() -> None:
    """Every authoring key sourced from the reference tree still reads what it emits.

    ⚠ **Compared whole, key for key, because every key this dump emits is spliced.** The
    two gates above compare named axes out of a larger dump; here the dump *is* the
    manifest's platform half, so anything it emits that the committed file does not
    carry is a stale contract.

    ⚠⚠ **A green row here is weaker evidence than a green station row, and the reason is
    structural rather than incidental.** The station dump asks a *built registry* which
    flows it wired; this one reads an `enum`, a `match` and a set of `const`s, because
    the platform has no runtime object to interrogate. So this gate catches a
    reference-side change that reaches one of those rosters, and cannot catch a
    reference-side change that should have reached one and did not — a new `Expr`
    variant left out of `sample_nodes`, a new `reject_unknown_keys` const nobody added
    to `schema_fields`. Python's introspective derivation still covers exactly that gap
    for the *checker's* tree (`test_authoring_freeze_manifest.py`), which is why the
    flip kept it rather than deleting it.
    """
    manifest = json.loads(
        (DOCS_DIR / "authoring-reference.manifest.json").read_text(encoding="utf-8")
    )
    dump = _rust_inventory(RUST_AUTHORING_DIR, "dump_authoring_inventory")

    assert set(dump) == _AUTHORING_DUMP_KEYS, (
        f"dump_authoring_inventory dumps {sorted(dump)}, not "
        f"{sorted(_AUTHORING_DUMP_KEYS)} — a new key has to be classified in that "
        f"manifest's _authority block before it can be frozen, and one the reference "
        f"cannot honestly produce (a hash of a Python-generated vector file) must not "
        f"enter at all."
    )
    assert dump["flow_types"], "no flow types compared"

    for key in sorted(dump):
        assert dump[key] == manifest[key], (
            f"authoring {key} diverges between the Rust tree and the frozen manifest:\n"
            f"  reference: {json.dumps(dump[key])[:300]}\n"
            f"  manifest:  {json.dumps(manifest[key])[:300]}\n"
            "⚠ This manifest is generated FROM this dump (slice 8), so this is NOT a "
            "port-vs-port divergence: the reference tree's author-facing surface has "
            "changed and the committed manifest has not been regenerated. Moving the "
            "grammar, the file schema, the flow-type registry or the loader vocabulary "
            "is an unfreeze — follow the ceremony in docs/authoring-reference.md, then "
            "`cd rust && cargo run --example dump_authoring_inventory -- "
            "--write-manifest` (slice C7 moved the writer here). If you did not "
            "mean to change what authors write against, the finding is whatever moved."
        )


def test_the_dump_key_sets_are_the_ones_the_generators_consume() -> None:
    """⚠ The dump key set exists TWICE per contract — tie the copies, don't restate.

    Each manifest generator asserts the dump's exact key set before splicing (a forcing
    function: a new key stops regeneration until someone classifies it), and this module
    asserts the same set again for the staleness gate. Both copies are correct today and
    a negative control proved each bites — but the failure is **one-sided**: widen the
    generator's copy and forget this one, and regeneration accepts the new key while
    this gate reddens with a message blaming the *dump*, the wrong place to look.

    ⚠ That is the *"a rule with two copies has one that is stale"* hazard this repo
    keeps re-learning, and slice 6 answered it once already — `RUST_AUTHORED` is not
    restated in the manifest's `_authority` block, it is **checked against** it. Same
    move here: the generators own the definition, this asserts agreement, and nobody
    writes a third copy.

    ⚠⚠ **THE BIOSPHERE AND AUTHORING ROWS LEFT WITH THEIR WRITERS (SLICE C7), AND
    THEIR ABSENCE IS THE POINT.** Neither contract has a generator to tie to any more:
    the reference writes those manifests itself, so the *second* declaration of the key
    set — the one a generator kept in order to refuse an unclassified key — does not
    exist, and a row here would be comparing this module against itself.

    ⚠ **The reason recorded when the biosphere row left was too broad, and the
    authoring case is what exposed it.** It read "nothing *consumes* the dump", which
    was true there and is false here: ``dump_authoring_inventory`` is still consumed,
    by :func:`test_rust_inventory_equals_the_frozen_manifest` in this very module. What
    actually licenses the removal is narrower — there is no longer a *second copy* of
    the key set to hold equal, because the copy lived in the writer. Same outcome, and
    a docstring carrying a reason that is not the reason is the defect class this repo
    keeps recording.

    What replaced the forcing function is not this test — it is ``set(dump) ==
    dump_keys`` in the two staleness gates (a new dump key still stops them until
    someone classifies it) and, for the manifest side,
    ``tests/crossport/test_manifest_writer.py``, which compares the whole committed file
    against a regeneration. ⚠ Neither row comes back when the station writer lands;
    that row *leaves* with it, and this test goes with it.

    Imported inside the test (with ``tests/`` put on the path the way this directory
    already reaches ``golden_platform``) so importing the generators is not a collection
    -time cost for the rest of the file.
    """
    import sys  # noqa: PLC0415

    sys.path.insert(0, str(REPO_ROOT / "tests"))
    import test_station_freeze_manifest  # noqa: PLC0415

    # ⚠ De-looped when the authoring row left: a one-element `for` is one deletion
    # from asserting nothing, and the deletion is *scheduled* here — the station row
    # leaves when its writer lands, and this test goes with it. Slice C6 recorded the
    # same hazard on a surviving single arm.
    theirs = test_station_freeze_manifest._RUST_DUMP_KEYS
    assert theirs == _STATION_DUMP_KEYS, (
        "the station dump's key set is declared twice and the copies disagree:\n"
        f"  this gate expects:     {sorted(_STATION_DUMP_KEYS)}\n"
        f"  the generator expects: {sorted(theirs)}\n"
        "The generator's copy is the definition — it is what stops a regeneration "
        "from splicing an unclassified key. Fix this module to match it, and read "
        "that module's _AUTHORITY before concluding the new key belongs at all."
    )


def test_the_station_aux_axis_is_empty_by_delegation() -> None:
    """The station `aux_set` is empty, so its parity row proves nothing on its own.

    ⚠ Recorded rather than papered over. `[] == []` is satisfied by a dump that never
    reached the aux accessor at all, which is exactly the defect shape slice 2 was
    caught on (four negative controls, all on one of the two traits). Two things stand
    in for the missing teeth, and neither is this assertion:

    * the **biosphere** case exercises the identical code path non-trivially — the same
      `registry.aux_processes()` walk, against three frozen names;
    * a **measured negative control** on the station side, run when slice 3 landed:
      wiring one aux process into a canonical station build turns the station row red,
      on the `aux_set` assertion specifically.

    ⚠⚠ **Slice 7 raised the stakes here, and the control was re-run against the new
    path.** The frozen `aux_set` is no longer Python's derivation — it is spliced in
    from this dump, so an empty list is *written into* the manifest rather than merely
    compared against one. Slice 6's two-direction rename control is unrunnable on this
    axis (there is no station aux process to rename), so the substitute is the wiring
    control above, re-measured through the regeneration path: the manifest gains the
    name and `test_frozen_station_aux_set_is_complete` goes red.

    What this test owns is the *reason* the set is empty — the siblings and seams are
    all conserved-quantity flows, and the biosphere's accumulators live in the slow
    registry the station manifest delegates away. If a station-side aux process is ever
    added, this goes red and the parity row above becomes load-bearing on its own.
    """
    manifest = json.loads(
        (DOCS_DIR / "station-reference.manifest.json").read_text(encoding="utf-8")
    )
    assert manifest["aux_set"] == [], (
        "the station manifest now freezes aux processes — the empty-set caveat in "
        "test_rust_inventory_equals_the_frozen_manifest no longer applies, and that "
        "parity row now has teeth of its own"
    )
    assert manifest["delegates_to"] == "docs/biosphere-reference.manifest.json"
