"""Reference flip, slice 3: the Rust port's own inventory vs. the frozen manifests.

The pilot with zero blast radius. A Rust program builds the canonical registries and
dumps the flow set / aux set it derives from them; this gate asserts that dump equals
the **existing, still-Python-anchored** manifest. Nothing is re-anchored, no golden
moves, no band is touched — the point is to establish that the port can *express* the
completeness contract before slice 4 moves the reference onto it, because completeness
is the axis the flip is riskiest for
(`docs/plans/post-roadmap-reference-flip.md` §2b).

**Why this is a real comparison and not a mirror.** The three sets involved have three
independent origins: Rust's names are hand-written `type_name()` literals (slice 2 chose
required-and-hand-written *over* the zero-cost automatic derivation, precisely so a
rename would show up here); Python's come from `type(flow).__name__` over its own
registries; the manifest is the committed artifact regenerated from Python. So a
Rust-vs-manifest disagreement is a genuine finding, not a round trip.

⚠⚠ **The manifests' third axis, `param_files`, is deliberately NOT compared, and the
exclusion is a finding rather than a simplification.** The slice was planned as "flow
set / aux set / **param file list**", and the port turns out to have no referent for the
third: Rust reads no YAML. It reads `biosphere_params.txt` / `sibling_params.txt` /
`station_params.txt`, all three **generated by Python**
(`tests/crossport/gen_*_params.py`) from the frozen loaders, as flat `name → hexfloat`
lines. Their prefixes are the generator's naming and not filenames — `photo.` against
`photosynthesis.yaml`, three prefixes (`pheno.` / `vern.` / photoperiod) out of the
single `phenology.yaml`, 17 loaders against 15 frozen files — and the sibling/station
files carry no prefix at all. Anything Rust printed under that key would be the Python
list travelling through Rust and back, so the gate would compare Python against Python:
the self-referential shape this repo already had to dissolve once, for the RNG vectors.

⚠ **The knock-on is slice 6's, and is recorded in the plan rather than resolved here:**
`param_files` cannot be re-anchored to Rust until Rust is the thing that loads the YAML,
which is **slice 9's** decision. So slice 6 must either declare that axis explicitly
Python-retained with a stated reason, or wait for slice 9 — which inverts the plan's
`9 depends on 6` ordering.

⚠ **Authoring is out of scope, on slice 2's evidence rather than by category.** The
authoring manifest's inventory is a different surface (grammar, VM node/op set,
flow-type registry) with no flow/aux registry axis, and the divergence that *would* have
made it urgent — a port that lowered every authored flow to the generic declarative one
and so reported a wrong inventory — was checked and cleared in slice 2: both ports make
the same distinction at the same point. Slice 8 owns that manifest.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
DOCS_DIR = REPO_ROOT / "docs"
RUST_DOMAINS_DIR = REPO_ROOT / "rust" / "crates" / "domains"
RUST_STATION_DIR = REPO_ROOT / "rust" / "crates" / "station"

# The axes the port can independently express, and therefore the ones compared. ⚠ This
# is asserted as the dump's *exact* key set, not read as a filter: adding `param_files`
# (or anything else) to a dump program turns this gate red until whoever did it has read
# the module docstring explaining why that key cannot be a parity axis. A filter would
# have let the tautology in silently.
_COMPARED_AXES = frozenset({"flow_set", "aux_set"})

# (label, crate dir, example, manifest). One per manifest that carries a
# registry-derived inventory; the biosphere is delegated out of the station manifest, so
# the two sets are disjoint by contract and each is checked against its own file.
_CASES = [
    (
        "biosphere",
        RUST_DOMAINS_DIR,
        "dump_biosphere_inventory",
        "biosphere-reference.manifest.json",
    ),
    (
        "station",
        RUST_STATION_DIR,
        "dump_station_inventory",
        "station-reference.manifest.json",
    ),
]


def _rust_inventory(crate_dir: Path, example: str) -> dict:
    """Run an inventory dump example and parse its JSON stdout."""
    proc = subprocess.run(
        ["cargo", "run", "-q", "--example", example],
        cwd=crate_dir,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, f"cargo run {example} failed:\n{proc.stderr}"
    return json.loads(proc.stdout)


@pytest.mark.skipif(shutil.which("cargo") is None, reason="cargo not installed")
@pytest.mark.parametrize("label,crate_dir,example,manifest_name", _CASES)
def test_rust_inventory_equals_the_frozen_manifest(
    label: str, crate_dir: Path, example: str, manifest_name: str
) -> None:
    """Rust's derived flow/aux inventory equals the committed manifest's, set for set.

    Runs wherever `cargo` is on PATH, and on the `crossport` CI job — which invokes
    `uv run pytest tests/crossport/` on the **directory**, so a new file here is
    collected rather than needing to be listed. (Checked, not inherited: this repo has
    two recorded green-by-skip incidents.)
    """
    manifest = json.loads((DOCS_DIR / manifest_name).read_text(encoding="utf-8"))
    dump = _rust_inventory(crate_dir, example)

    assert set(dump) == _COMPARED_AXES, (
        f"{example} dumps {sorted(dump)}, not {sorted(_COMPARED_AXES)} — see this "
        f"module's docstring before adding an axis (a param-file list would make this "
        f"gate compare Python against Python)"
    )

    # ⚠ Guard the comparison itself, not just its result. An equality against an empty
    # frozen list is a green test that has checked nothing, and the flow axis is where
    # this gate's teeth are. (The *aux* axis is legitimately empty on the station side —
    # see `test_the_station_aux_axis_is_empty_by_delegation`, which states that rather
    # than letting `[] == []` pass as evidence.)
    assert manifest["flow_set"], f"{manifest_name} freezes no flows — nothing compared"

    for axis in sorted(_COMPARED_AXES):
        assert dump[axis] == manifest[axis], (
            f"{label} {axis} diverges between the Rust port and {manifest_name}:\n"
            f"  only in Rust:     {sorted(set(dump[axis]) - set(manifest[axis]))}\n"
            f"  only in manifest: {sorted(set(manifest[axis]) - set(dump[axis]))}\n"
            f"⚠ Before treating this as a port bug, check the registry SELECTION in "
            f"the dump example against the Python gate's `_canonical_registries()` / "
            f"`_station_registries()` — a mis-mirrored build option (self-discharge, "
            f"with_harvest, the fast-vs-slow registry index) reads exactly like a "
            f"divergence and is not one. If the selection is right, this is a finding "
            f"to hunt and it STOPS the slice; do not adjust either side to agree."
        )


def test_the_station_aux_axis_is_empty_by_delegation() -> None:
    """The station `aux_set` is empty, so its parity row proves nothing on its own.

    ⚠ Recorded rather than papered over. `[] == []` is satisfied by a dump that never
    reached the aux accessor at all, which is exactly the defect shape slice 2 was
    caught on (four negative controls, all on one of the two traits). Two things stand
    in for the missing teeth, and neither is this assertion:

    * the **biosphere** case exercises the identical code path non-trivially — the same
      `registry.aux_processes()` walk, against three frozen names;
    * a **measured negative control** on the station side, run when the slice landed:
      wiring one aux process into a canonical station build turns the station row red,
      on the `aux_set` assertion specifically.

    What this test owns is the *reason* the set is empty — the siblings and seams are
    all conserved-quantity flows, and the biosphere's accumulators live in the slow
    registry the station manifest delegates away. If a station-side aux process is ever
    added, this goes red and the parity row above becomes load-bearing on its own.
    """
    manifest = json.loads(
        (DOCS_DIR / "station-reference.manifest.json").read_text(encoding="utf-8")
    )
    assert manifest["aux_set"] == [], (
        "the station manifest now freezes aux processes — the empty-set caveat in "
        "test_rust_inventory_equals_the_frozen_manifest no longer applies, and that "
        "parity row now has teeth of its own"
    )
    assert manifest["delegates_to"] == "docs/biosphere-reference.manifest.json"
