//! Cross-port authoring parity — the Rust side of the Phase-9 Step-4a gate.
//!
//! Reads the two committed vector files generated by
//! `tests/crossport/gen_authoring_vectors.py` and asserts:
//!
//! * **Parse-parity (Tier-0 structural):** each accept case parses to an AST whose
//!   canonical S-expr equals the file's — the *same rate string lowers to the same AST*
//!   in both ports (the sole parse-parity risk surface: precedence/associativity + the
//!   exact-literal `Const` spelling). Each reject case must error in Rust too (the
//!   deferred grammar / malformed input — message text is NOT pinned).
//! * **Trajectory-parity (Tier-1 bit-exact):** the two authored scenarios — the frozen
//!   `SelfDischarge` re-expression anchor and the synthetic full-VM scenario — rebuilt
//!   in Rust from the *same parsed rate strings*, run under Euler AND RK4, match the
//!   file's per-step stock amounts to the IEEE-754 bit (via the hex-float codec).
//!
//! `src/authoring` + `src/simcore/expr.py` are the reference; proving Rust == Python is
//! the goal (no external anchor — like the engine vectors). `test_crossport.py` guards
//! the files stay in sync with `render()`.

use std::collections::BTreeMap;

use authoring::{parse_rate_expr, render_sexpr};
use simcore::boundary;
use simcore::environment::{constant, SourceResolver};
use simcore::expr::DeclarativeFlow;
use simcore::flow::Flow;
use simcore::hexfloat;
use simcore::integrator::{EulerIntegrator, Rk4Integrator};
use simcore::quantities::{Quantity, StockKind};
use simcore::registry::Registry;
use simcore::state::{State, Stock};

const PARSE_VECTORS: &str = include_str!("data/parse_vectors.txt");
const TRAJ_VECTORS: &str = include_str!("data/traj_vectors.txt");

// --------------------------------------------------------------------------- //
// Parse-parity                                                                //
// --------------------------------------------------------------------------- //
#[test]
fn parse_parity_accept_and_reject() {
    let mut accepts = 0usize;
    let mut rejects = 0usize;
    for line in PARSE_VECTORS.lines() {
        if line.starts_with('#') {
            continue;
        }
        // Split on the FIRST tab (kind) — the input field may itself contain no tab,
        // but the empty/whitespace reject cases must keep their exact bytes.
        let (kind, rest) = match line.split_once('\t') {
            Some(pair) => pair,
            None => continue,
        };
        match kind {
            "accept" => {
                // rest = input <TAB> canonical-sexpr
                let (input, expected) = rest
                    .split_once('\t')
                    .unwrap_or_else(|| panic!("malformed accept line: {line:?}"));
                let ast = parse_rate_expr(input)
                    .unwrap_or_else(|e| panic!("accept case {input:?} failed to parse: {e}"));
                let got = render_sexpr(&ast);
                assert_eq!(
                    got, expected,
                    "parse-parity S-expr mismatch for {input:?}"
                );
                accepts += 1;
            }
            "reject" => {
                // rest is the whole input (may be empty or whitespace-only).
                assert!(
                    parse_rate_expr(rest).is_err(),
                    "reject case {rest:?} unexpectedly parsed"
                );
                rejects += 1;
            }
            other => panic!("unknown vector kind {other:?} in {line:?}"),
        }
    }
    assert!(accepts >= 15, "expected many accept cases, got {accepts}");
    assert!(rejects >= 10, "expected many reject cases, got {rejects}");
}

// --------------------------------------------------------------------------- //
// Trajectory-parity                                                           //
// --------------------------------------------------------------------------- //
/// The expected per-step amounts keyed by (scenario, scheme, n, stock_id).
type Expected = BTreeMap<(String, String, u64, String), u64>; // value = f64 bits

fn load_expected() -> Expected {
    let mut expected: Expected = BTreeMap::new();
    for line in TRAJ_VECTORS.lines() {
        if line.starts_with('#') {
            continue;
        }
        let fields: Vec<&str> = line.split('\t').collect();
        if fields.first() != Some(&"stock") {
            continue; // meta lines checked separately below
        }
        // stock <TAB> scenario <TAB> scheme <TAB> n <TAB> stock_id <TAB> hex
        let scenario = fields[1].to_string();
        let scheme = fields[2].to_string();
        let n: u64 = fields[3].parse().unwrap();
        let stock_id = fields[4].to_string();
        let bits = hexfloat::parse(fields[5]).unwrap().to_bits();
        expected.insert((scenario, scheme, n, stock_id), bits);
    }
    expected
}

fn energy_stock(id: &str, domain: &str, amount: f64, kind: StockKind) -> Stock {
    Stock::new(
        id.to_string(),
        domain.to_string(),
        Quantity::Energy,
        "J".to_string(),
        amount,
        kind,
        0.0,
        false,
        BTreeMap::new(),
    )
    .unwrap()
}

fn carbon_stock(id: &str, domain: &str, amount: f64, kind: StockKind) -> Stock {
    Stock::new(
        id.to_string(),
        domain.to_string(),
        Quantity::Carbon,
        "mol".to_string(),
        amount,
        kind,
        0.0,
        false,
        BTreeMap::new(),
    )
    .unwrap()
}

/// A built scenario: its stocks, a fresh flow set, the resolver, and `dt`.
type Scenario = (BTreeMap<String, Stock>, Vec<Box<dyn Flow>>, SourceResolver, f64);

/// The SelfDischarge re-expression anchor: rate `k·battery`, −1/+1 ENERGY split. `k` is
/// the frozen `self_discharge` value (from the sibling-params hex-float, so the authored
/// constant IS the frozen one). Built from the *parsed* rate string.
fn self_discharge_scenario() -> Scenario {
    // The frozen k, hex from rust/crates/domains/src/sibling_params.txt.
    let k = hexfloat::parse("0x1.5798ee2308c3ap-27").unwrap();
    let mut stocks = BTreeMap::new();
    stocks.insert(
        "power.battery".to_string(),
        energy_stock("power.battery", "power", 1.0e7, StockKind::Pool),
    );
    stocks.insert(
        "boundary.waste_heat".to_string(),
        energy_stock("boundary.waste_heat", "boundary", 0.0, StockKind::Boundary),
    );
    let rate = parse_rate_expr(r#"param("self_discharge_rate") * stock("power.battery")"#)
        .unwrap();
    let flow = DeclarativeFlow::new(
        "power.self_discharge".to_string(),
        0,
        rate,
        vec![
            ("power.battery".to_string(), -1.0),
            ("boundary.waste_heat".to_string(), 1.0),
        ],
        vec![("self_discharge_rate".to_string(), k)],
    );
    (stocks, vec![Box::new(flow)], SourceResolver::empty(), 3600.0)
}

/// The synthetic full-VM scenario: a forced inflow whose rate uses
/// ForcingRef/StepN/Const/Mul/Add/Sub, and a donor leak whose rate uses Neg over a
/// product. Sized well-fed (rationed == 0, events == ()).
fn synthetic_scenario() -> Scenario {
    let mut stocks = BTreeMap::new();
    stocks.insert(
        "sim.pool".to_string(),
        carbon_stock("sim.pool", "sim", 100.0, StockKind::Pool),
    );
    stocks.insert(
        "boundary.src".to_string(),
        boundary::source("boundary.src".to_string(), Quantity::Carbon, 0.0, true).unwrap(),
    );
    stocks.insert(
        "boundary.snk".to_string(),
        boundary::sink("boundary.snk".to_string(), Quantity::Carbon, 0.0).unwrap(),
    );
    let forced_rate = parse_rate_expr(r#"forcing("q") + n * param("g") - param("c")"#).unwrap();
    let forced = DeclarativeFlow::new(
        "sim.forced_in".to_string(),
        0,
        forced_rate,
        vec![
            ("boundary.src".to_string(), -1.0),
            ("sim.pool".to_string(), 1.0),
        ],
        vec![("c".to_string(), 0.5), ("g".to_string(), 0.01)],
    );
    let leak_rate = parse_rate_expr(r#"-(param("k") * stock("sim.pool"))"#).unwrap();
    let leak = DeclarativeFlow::new(
        "sim.leak".to_string(),
        0,
        leak_rate,
        vec![
            ("sim.pool".to_string(), 1.0),
            ("boundary.snk".to_string(), -1.0),
        ],
        vec![("k".to_string(), 0.03)],
    );
    let mut forcings = std::collections::HashMap::new();
    forcings.insert("q".to_string(), constant(2.0).unwrap());
    let resolver = SourceResolver::new(forcings, std::collections::HashMap::new()).unwrap();
    (stocks, vec![Box::new(forced), Box::new(leak)], resolver, 0.5)
}

/// One step under the chosen scheme (the two integrators are distinct types).
fn step_report(
    scheme: &str,
    reg: Registry,
    cur: &State,
    env: &SourceResolver,
    dt: f64,
) -> simcore::integrator::StepReport {
    if scheme == "euler" {
        EulerIntegrator::new(reg).step_report(cur, env, dt).unwrap()
    } else {
        Rk4Integrator::new(reg).step_report(cur, env, dt).unwrap()
    }
}

/// Run one scenario under both schemes and check every stock at every step bit-exact.
/// `build_flows` yields a fresh flow set per call (a `Box<dyn Flow>` is not `Clone`, and
/// `Registry` consumes them), so a registry is rebuilt each step — cheap for these tiny
/// graphs and keeps the integrator construction identical to `EulerIntegrator::new`.
fn check_scenario(
    scenario: &str,
    stocks: &BTreeMap<String, Stock>,
    build_flows: impl Fn() -> Vec<Box<dyn Flow>>,
    env: &SourceResolver,
    dt: f64,
    steps: u64,
    expected: &Expected,
) {
    for scheme in ["euler", "rk4"] {
        let mut cur = State::new(0, stocks.clone(), 0, BTreeMap::new()).unwrap();
        for n in 0..=steps {
            if n > 0 {
                let reg = Registry::flows_only(build_flows(), stocks).unwrap();
                let report = step_report(scheme, reg, &cur, env, dt);
                assert_eq!(report.rationed, 0, "{scenario}/{scheme} n={n} rationed");
                assert!(report.events.is_empty(), "{scenario}/{scheme} n={n} events");
                cur = report.state;
            }
            for (sid, stock) in &cur.stocks {
                let key = (scenario.to_string(), scheme.to_string(), n, sid.clone());
                let want = expected
                    .get(&key)
                    .unwrap_or_else(|| panic!("no expected value for {key:?}"));
                assert_eq!(
                    stock.amount.to_bits(),
                    *want,
                    "trajectory bit mismatch {scenario}/{scheme} n={n} {sid}: \
                     got {} want {}",
                    hexfloat::format(stock.amount),
                    hexfloat::format(f64::from_bits(*want)),
                );
            }
        }
    }
}

#[test]
fn trajectory_parity_self_discharge_and_synthetic() {
    let expected = load_expected();

    let (stocks, _flows, env, dt) = self_discharge_scenario();
    check_scenario(
        "self_discharge",
        &stocks,
        || self_discharge_scenario().1,
        &env,
        dt,
        24,
        &expected,
    );

    let (stocks, _flows, env, dt) = synthetic_scenario();
    check_scenario(
        "synthetic",
        &stocks,
        || synthetic_scenario().1,
        &env,
        dt,
        24,
        &expected,
    );
}
